In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

import missingno as ms
%matplotlib inline
train_data = []
data_files = ['/content/drive/MyDrive/youtube/Youtube01.csv','/content/drive/MyDrive/youtube/Youtube02-KatyPerry.csv','/content/drive/MyDrive/youtube/Youtube03-LMFAO.csv','/content/drive/MyDrive/youtube/Youtube04-Eminem.csv','/content/drive/MyDrive/youtube/Youtube05-Shakira.csv']
for file in data_files:
    data = pd.read_csv(file)
    train_data.append(data)
train_data = pd.concat(train_data)
train_data.head(15)

## Function which drops the given features from the given dataframe


COMMENT_ID            AUTHOR  \
0   LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1   LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2   LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3           z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4           z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   
5   LZQPQhLyRh9-wNRtlZDM90f1k0BrdVdJyN_YsaSwfxc      Jason Haddad   
6           z13lfzdo5vmdi1cm123te5uz2mqig1brz04    ferleck ferles   
7         z122wfnzgt30fhubn04cdn3xfx2mxzngsl40k      Bob Kanowski   
8           z13ttt1jcraqexk2o234ghbgzxymz1zzi04              Cony   
9           z12avveb4xqiirsix04chxviiljryduwxg0       BeBe Burkey   
10        z13auhww3oufjn1qo04ci3grqqjmfjexxuo0k         Huckyduck   
11            z13xit5agm2zyh4f523rst2gowmbx5bml       Lone Twistt   
12            z13pejoiuozwxtdu323dspopnri4xts0f      Archie Lewis   
13        z121zxaxsq25z5k5o04ch1o5jqqfij3gtm40k   TheUploadaddict   
14        z12oglnpoq3gjh4om04cfdlbgp2uepyytpw0k    Francisco Nora   

                   DATE                                            CONTENT  \
0   2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1   2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2   2013-11-08T17:34:21             just for test I have to say murdev.com   
3   2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4   2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   
5   2013-11-26T02:55:11  Hey, check out my new website!! This site is a...   
6   2013-11-27T21:39:24                          Subscribe to my channel    
7   2013-11-28T12:33:27  i turned it on mute as soon is i came on i jus...   
8   2013-11-28T16:01:47    You should check my channel for Funny VIDEOS!!   
9   2013-11-28T16:30:13  and u should.d check my channel and tell me wh...   
10  2013-11-28T17:06:17                               Hey subscribe to me   
11  2013-11-28T17:34:55   Once you have started reading do not stop. If...   
12  2013-11-28T17:54:39               https://twitter.com/GBphotographyGB   
13  2013-11-28T18:12:12                            subscribe like comment   
14  2013-11-28T19:52:35  please like :D https://premium.easypromosapp.c...   

    CLASS  
0       1  
1       1  
2       1  
3       1  
4       1  
5       1  
6       1  
7       0  
8       1  
9       1  
10      1  
11      1  
12      1  
13      1  
14      1

In [3]:
def drop_fectures(features,data):
    data.drop(features,axis=1,inplace=True)
drop_fectures(['COMMENT_ID','AUTHOR','DATE'],train_data)
train_data.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 1956 entries, 0 to 369
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   CONTENT  1956 non-null   object
 1   CLASS    1956 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 45.8+ KB


In [4]:
import re
re.findall("[A-Za-z]+","Hey Ravi57,How are you doing?")

['Hey', 'Ravi', 'How', 'are', 'you', 'doing']

In [5]:
def process_content(content):
    return " ".join(re.findall("[A-Za-z]+",content.lower()))

In [6]:
train_data['processed_content'] = train_data['CONTENT'].apply(process_content)

In [7]:
train_data.head(15)

CONTENT  CLASS  \
0   Huh, anyway check out this you[tube] channel: ...      1   
1   Hey guys check out my new channel and our firs...      1   
2              just for test I have to say murdev.com      1   
3    me shaking my sexy ass on my channel enjoy ^_^       1   
4             watch?v=vtaRGgvGtWQ   Check this out .      1   
5   Hey, check out my new website!! This site is a...      1   
6                           Subscribe to my channel       1   
7   i turned it on mute as soon is i came on i jus...      0   
8     You should check my channel for Funny VIDEOS!!      1   
9   and u should.d check my channel and tell me wh...      1   
10                               Hey subscribe to me      1   
11   Once you have started reading do not stop. If...      1   
12               https://twitter.com/GBphotographyGB      1   
13                            subscribe like comment      1   
14  please like :D https://premium.easypromosapp.c...      1   

                                    processed_content  
0   huh anyway check out this you tube channel kob...  
1   hey guys check out my new channel and our firs...  
2              just for test i have to say murdev com  
3          me shaking my sexy ass on my channel enjoy  
4                  watch v vtarggvgtwq check this out  
5   hey check out my new website this site is abou...  
6                             subscribe to my channel  
7   i turned it on mute as soon is i came on i jus...  
8        you should check my channel for funny videos  
9   and u should d check my channel and tell me wh...  
10                                hey subscribe to me  
11  once you have started reading do not stop if y...  
12                  https twitter com gbphotographygb  
13                             subscribe like comment  
14  please like d https premium easypromosapp com ...

In [8]:
drop_fectures(['CONTENT'],train_data)

In [9]:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_data['processed_content'],train_data['CLASS'],test_size=0.2,random_state=57)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(stop_words='english')
x_train_counts = count_vect.fit_transform(x_train)
x_train_counts.shape


(1564, 3345)

In [11]:
from sklearn.feature_extraction.text import TfidfTransformer
tranformer = TfidfTransformer()
x_train_tfidf = tranformer.fit_transform(x_train_counts)
x_train_tfidf.shape


(1564, 3345)

In [12]:
x_test_counts = count_vect.transform(x_test)
x_test_counts

<392x3345 sparse matrix of type '<class 'numpy.int64'>'
	with 2384 stored elements in Compressed Sparse Row format>

In [13]:
x_test_tfidf = tranformer.transform(x_test_counts)
x_test_tfidf

<392x3345 sparse matrix of type '<class 'numpy.float64'>'
	with 2384 stored elements in Compressed Sparse Row format>

In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train_tfidf,y_train)

LogisticRegression()

In [15]:
predictions = model.predict(x_test_tfidf)


In [19]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
confusion_matrix(y_test,predictions)

array([[176,   5],
       [ 24, 187]])

In [20]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92       181
           1       0.97      0.89      0.93       211

    accuracy                           0.93       392
   macro avg       0.93      0.93      0.93       392
weighted avg       0.93      0.93      0.93       392



In [21]:
from sklearn.metrics import matthews_corrcoef 
print(matthews_corrcoef(y_test,predictions))


0.8562917859605038


In [22]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train_tfidf,y_train)

RandomForestClassifier()

In [23]:
predictions = model.predict(x_test_tfidf)
confusion_matrix(y_test,predictions)

array([[177,   4],
       [ 16, 195]])

In [24]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       181
           1       0.98      0.92      0.95       211

    accuracy                           0.95       392
   macro avg       0.95      0.95      0.95       392
weighted avg       0.95      0.95      0.95       392



In [25]:
from sklearn.metrics import matthews_corrcoef 
print(matthews_corrcoef(y_test,predictions))

0.8995309793158213


In [26]:
from sklearn.naive_bayes import BernoulliNB

In [27]:
model = BernoulliNB()
model.fit(x_train_tfidf,y_train)

BernoulliNB()

In [28]:
predictions = model.predict(x_test_tfidf)
confusion_matrix(y_test,predictions)

array([[180,   1],
       [ 48, 163]])

In [29]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.79      0.99      0.88       181
           1       0.99      0.77      0.87       211

    accuracy                           0.88       392
   macro avg       0.89      0.88      0.87       392
weighted avg       0.90      0.88      0.87       392



In [30]:
from sklearn.metrics import matthews_corrcoef 
print(matthews_corrcoef(y_test,predictions))

0.7751382405912144


In [31]:
from sklearn import tree


In [32]:
model = tree.DecisionTreeClassifier()
model.fit(x_train_tfidf,y_train)

DecisionTreeClassifier()

In [33]:
predictions = model.predict(x_test_tfidf)
confusion_matrix(y_test,predictions)

array([[170,  11],
       [ 16, 195]])

In [34]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.91      0.94      0.93       181
           1       0.95      0.92      0.94       211

    accuracy                           0.93       392
   macro avg       0.93      0.93      0.93       392
weighted avg       0.93      0.93      0.93       392



In [35]:
from sklearn.metrics import matthews_corrcoef 
print(matthews_corrcoef(y_test,predictions))

0.8619876354031328
